name: Commit Conditions
description: Examines the commit in a triggered action and outputs a result based on examined conditions
branding:
  icon: git-commit
  color: blue
runs:
  using: node16
  main: dist/index.mjs
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  success-commit-message:
    description: >
      Action returns true if commit message contains this message.
    required: false
  fail-commit-message:
    description: >
      Action returns false if commit message contains this message.
    required: false
  excludes:
    description: >
      Comma separated list of file paths. Accepts glob patterns.
      Action will return false if commit contains only these changed files. 
    required: false
  includes:
    description: >
      Aomma separated list of file paths. Accepts glob patterns.
      Action will return true if commit contains any of these changed files.
    required: false
  approve:
    description: >
      if set to true, PR will be auto approved based on conditions
    required: false
    default: false
  approveMessage:
    description: >
      Comment to set if auto approving PR.
    required: false
outputs:
  result:
    description: >
      Result of checked conditions ('true' or 'false')
